config/routes.rb
Rails.application.routes.draw do
 
  resources :groups
  resources :user_groups
  resources :orders
  resources :order_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  default_url_options :host => "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  root to: 'user#index'

  get '/friends/search/:input', to: 'friend#search'

  get '/friends', to: 'friend#friends_index'

  post '/friends', to: 'friend#add_friend'
  
  delete '/friends', to: 'friend#remove_friend'

  get '/all_notifications', to: 'notifications#showAllNotifications'

  get '/join/:order_id', to: 'notifications#join'
  get '/cancel/:order_id', to: 'notifications#cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  def index
    @user = current_user
    @details = OrderDetail.where(order_id: params[:order])
    @order = Order.find(params[:order])
    @newDetail = OrderDetail.new
    @users = OrderDetail.where(order_id: params[:order])
    @invited_users = InvitedUser.where(order_id: params[:order])
  end

  def create
  @detail = OrderDetail.new 
  @detail.user_id = current_user.id
  @detail.order_id = params[:order_id]
  @detail.item_name = params[:item]
  @detail.amount = params[:amount]
  @detail.price = params[:price]
  @detail.comment = params[:comment]
  @detail.save
  redirect_to :controller => 'order_details', :action => 'index' ,:order => params[:order_id]
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    @user = OrderDetail.find(params[:id])
    id = @user.order_id
    user_status = InvitedUser.where(order_id: id)
    @order = Order.find(id)
    if user_status == 0
      @order.invited = @order.invited - 1
      @order.save
    elsif user_status == 1
      @order.joined = @order.joined - 1
      @order.invited = @order.invited - 1
      @order.save
    end
    @user.delete
    redirect_to :controller => 'order_details', :action => 'index' ,:order => id
  end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/create.html.erb
<h1>OrderDetails#create</h1>
<p>Find me in app/views/order_details/create.html.erb</p>

<p>number : <%= @num%></p>

app/views/order_details/destroy.html.erb
<h1>OrderDetails#destroy</h1>
<p>Find me in app/views/order_details/destroy.html.erb</p>

app/views/order_details/edit.html.erb
<h1>OrderDetails#edit</h1>
<p>Find me in app/views/order_details/edit.html.erb</p>

app/views/order_details/index.html.erb
<p></p>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Item</th>
      <th scope="col">Amount</th>
      <th scope="col">Price</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
  <% @details.each do |detail| %>
    <tr>
    <td><%= User.find(detail.user_id).name%></td>
      <td><%= detail.item_name%></td>
      <td><%= detail.amount%></td>
      <td><%= detail.price%></td>
      <td style="display:flex;flex-direction:row; justify-content:space-between;align-items:center;">
      <%= detail.comment %>
      <% if current_user.id == detail.user_id && @order.status == 0%>
      <%= button_to 'delete' ,detail, method: :delete, class: "btn btn-danger"  %>
      <%end %>
      
      </td>
    </tr>
  <%end%>
  </tbody>
</table>


<% if @order.user_id == current_user.id %>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  <%= @order.invited%> friends invited,click to view
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">invited users</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
                <% @invited_users.each do |user| %>
                <% if user.status == 0 %>
                <h6><%= User.find(user.user_id).name %></h6>
                <% if user.user_id != current_user.id && @order.status ==0 %>
                <%= link_to 'remove', order_detail_path(:id => user.id) , method: :delete %>
                <%end %>
                <%end %>
                <%end %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>




<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
   <%= @order.joined%> friends joined,click to view
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">joined users</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="container">
        <% @invited_users.each do |user| %>
                    <% if user.status == 1 %>
                        <h3><%= User.find(user.user_id).name %></h3>
                            <% if user.user_id != current_user.id && @order.status ==0 %>
                            <%= link_to 'remove', order_detail_path(:id => user.id) , method: :delete %>
                            <%end %>
                    <%end %>
        <%end %>

    </div>
            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

 <%end%>











 <% if @order.status == 0 && InvitedUser.where(order_id: @order.id,user_id: current_user.id)[0].status == 1 %>


<div class="container" style="border-width: 10px; border-style:solid;border-radius:20px;padding:10px ; margin:10px;border-color:gray">
  <h2>Add Comment </h2>
  <%= form_for(@newDetail,:url => {:controller => "order_details", :action => "create"}) do |f| %>
  <div class="form-inline">
    <div class="form-group">
      <label for="item">Item:</label>
      <input type="text" class="form-control" required id="email" placeholder="Enter Item" name="item" style="margin:10px">
    </div>
    
    <div class="form-group">
      <label for="amount">Amount:</label>
      <input type="number" id="quantity" required name="amount" min="1" style="width:50px; margin:10px">
    </div>
    <div class="form-group">
      <label for="price">Price:</label>
      <input type="number" id="quantity" required name="price" min="1" style="width:50px; margin:10px">
    </div>
    <div class="form-group">
      <label for="comment">Comment:</label>
      <input type="text" class="form-control" required id="pwd" placeholder="Enter Comment" name="comment" style="margin:10px">
    </div>
     <input type="hidden" name="order_id" value = <%= @order.id%> >
    <button type="submit" class="btn btn-success" style="width:100px">Add</button>
  </div>
  <% end %>
</div>

<%end %>

app/views/order_details/new.html.erb
<h1>OrderDetails#new</h1>
<p>Find me in app/views/order_details/new.html.erb</p>

app/views/order_details/show.html.erb
<h1>OrderDetails#show</h1>
<p>Find me in app/views/order_details/show.html.erb</p>

app/views/order_details/update.html.erb
<h1>OrderDetails#update</h1>
<p>Find me in app/views/order_details/update.html.erb</p>