config/routes.rb
Rails.application.routes.draw do
 
  resources :groups
  resources :user_groups
  resources :orders
  resources :order_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  default_url_options :host => "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  root to: 'user#index'

  get '/friends/search/:input', to: 'friend#search'

  get '/friends', to: 'friend#friends_index'

  post '/friends', to: 'friend#add_friend'
  
  delete '/friends', to: 'friend#remove_friend'

  get '/all_notifications', to: 'notifications#showAllNotifications'

  get '/join/:order_id', to: 'notifications#join'
  get '/cancel/:order_id', to: 'notifications#cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name, presence:true, uniqueness:true
    belongs_to :user
    has_many :user_groups
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def show
    @groups = Group.where(user_id: current_user.id)
      @group = Group.find_by(id: params[:id], user_id: current_user.id)
        if @group.nil?
            flash[:group_error] = "There is no Group exists with this id"
            redirect_to :groups
        end
        @members = UserGroup.where(group_id: params[:id])
        @users = @members.map{
            |member| User.find(member.user_id)
        }
        @data = []
        @data << @group
        @data << @groups
        @data << @users
  end

  def create
    @group = Group.create(name: params[:name], user_id: current_user.id)
        if @group.persisted?  
            redirect_to :groups 
        else
            flash[:group_errors] = @group.errors.full_messages
            redirect_to :groups
        end
  end
  
  def destroy
    @group = Group.find_by(id: params[:id], user_id: current_user.id)
    if @group
        @group.destroy
        redirect_to :groups
    else
        flash[:group_error] = "You can't delete this group"
        redirect_to :groups
    end
    
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<div class="center">
    <h1>Groups</h1>

    <!-- Show error msgs -->
    <% if flash[:group_errors]%>
        <div class="alert alert-danger">
            <% flash[:group_errors].each do |msg|%>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </div>
    <% end %>
    <% if flash[:group_error]%>
        <div class="alert alert-danger">
            <li>
                <%= flash[:group_error] %>
            </li>
        </div>
    <% end %>

    <!-- Form for Creating new Group -->
    <%= form_with(url: "/groups") do %>
    <div class="form-inline align-items-center">
        <%= label_tag(:name, "Group", style:"margin-right:10px") %>
        <%= text_field_tag(:name, nil,class: "form-control") %>
        <%= submit_tag("Add", class: "btn btn-dark", style:"margin-left:30px") %>
    </div>
    <% end %>
    
    <div class="row" style="margin-top: 30px">

        <!-- Show Groups which the currnet user is admin in -->
        <div class= "col-sm">
            <h2>My Groups</h2>
            <ul class="list-group">
                <% @groups.each do |group| %>
                    <div class="group">
                    <p class="group-name"> <%= group.name %>  </p>
                        <%= link_to 'delete', group, method: :delete, class:"btn btn-danger" %>
                        <%=link_to 'show', group, class:"btn btn-primary showButton"%>
                   </div>
                <% end %>
            </ul>
        </div>

    </div>

</div>

app/views/groups/show.html.erb
<div class="center">
     <h1>Groups</h1>

    <!-- Form for Creating new Group -->
    <%= form_with(url: "/groups") do %>
    <div class="form-inline align-items-center">
        <%= label_tag(:name, "Group", style:"margin-right:10px") %>
        <%= text_field_tag(:name, nil,class: "form-control") %>
        <%= submit_tag("Add", class: "btn btn-dark", style:"margin-left:30px") %>
    </div>
    <% end %>

    <div class="row" style="margin-top: 30px">
        <div class= "col-sm">
            <h2>My Groups</h2>
            <ul class="list-group">
                <% @data[1].each do |group| %>
                <div class="group">
                    <h2> <%= group.name %>  </h2>
                        <%= link_to 'delete', group, method: :delete, class:"btn btn-danger" %>
                        <%=link_to 'add user', group, class:"btn btn-primary showButton"%>
                   
                    </div>
                <% end %>
            </ul>
        </div>
    
    
     <!-- Show group and its members-->
        <div class= "col-sm">
            <% if @data[0].name %>
                <h2><%= @data[0].name%></h2>
                    <% if flash[:user_group_errors]%>
                        <div class="alert alert-danger">
                        <% flash[:user_group_errors] do |msg| %>
                            <li>
                                <%= msg %>
                            </li>
                            <% end %>
                        </div>
                    <% end %>
                    <%= form_with(url: "/user_groups") do %>
                        <div class="form-inline align-items-center">
                            <%= hidden_field_tag(:group_id, @data[0].id) %>
                            <%= label_tag(:email, "Add member", style:"margin-right:10px") %>
                            <%= email_field_tag(:email, nil,class: "form-control") %>
                            <%= submit_tag("Add", class: "btn btn-dark", style:"margin-left:30px") %>
                        </div>
                    <% end %>
                    <div style="margin-top:20px;margin-left:70px">
                <% if @data[2] && @data[1].length > 0%>
                    <% @data[2].each do |user| %>
                        <p>
                            <%= user["name"] %> 
                                <%= link_to 'delete', user_group_url(:id =>@data[0].id, :user_id => user["id"]), method: :delete, class:"btn btn-danger" %>
                        </p>
                    <% end %>
                <% else %>
                    <p>There is no users yet </p>
                <% end %>
                </div>
            <% end %>

        </div>
</div>