config/routes.rb
Rails.application.routes.draw do
 
  resources :groups
  resources :user_groups
  resources :orders
  resources :order_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  default_url_options :host => "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  root to: 'user#index'

  get '/friends/search/:input', to: 'friend#search'

  get '/friends', to: 'friend#friends_index'

  post '/friends', to: 'friend#add_friend'
  
  delete '/friends', to: 'friend#remove_friend'

  get '/all_notifications', to: 'notifications#showAllNotifications'

  get '/join/:order_id', to: 'notifications#join'
  get '/cancel/:order_id', to: 'notifications#cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # belongs_to :order 
  has_many :invited_users
  has_many :orders
  # has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
  # has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  # has_many :groups, :class_name => 'Group', :foreign_key => 'user_id'
  has_many :user_groups, :class_name => 'UserGroup', :foreign_key => 'user_id'       

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def email_required?
    false
  end

  has_attached_file :avatar, :default_url => "/system/users/avatars/000/000/default/user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  has_many :following, :class_name => 'Friend', :foreign_key => 'user_id'
  has_many :followers, :class_name => 'Friend', :foreign_key => 'friend_id'

  has_many :friends
  has_many :notifications, foreign_key: :to_id

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user_orders = Order.where(user_id: current_user.id).reverse_order
    @friends_orders = Order.where(user_id: [current_user.friends.pluck("friend_id")]).reverse_order
  end
end

app/views/user/index.html.erb
<div class='home-main-div'>
    <div class="col-md-5">
        <div class='div-head' style="margin-right:270px"><h3>Latest Orders</h3></div>
        <div class = "panel">
            <br>
            <table class="table table-striped table-hover" style="width:500px">
            <thead>
            </thead>
            <tbody>
            <% @user_orders.each do |order| %>
                <tr class="">
                <td>
                    <a href="<%= order_path(order) %>">Order</a> for <%= order.order_for %> on<%= order.created_at.strftime(" %d of %b at %I:%M %P") %>
                </td>
                </tr>
            <% end %>
            </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-5">
      <div class='div-head' style="margin-right:300px"><h3>Friends Activity</h3></div>
      <div class="panel">
        <br>
        <table class="table table-striped table-hover" style="width:600px">
          <thead>
          </thead>
          <tbody id="f_activity">
            <% @friends_orders.each do |order| %>
              <tr class="">
                <td>
                <%= order.user.name %> has created an <%= link_to 'Order', order_path(order) %> for <%= order.order_for %> from <%= order.restaurant %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>