config/routes.rb
Rails.application.routes.draw do
 
  resources :groups
  resources :user_groups
  resources :orders
  resources :order_details
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  default_url_options :host => "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  root to: 'user#index'

  get '/friends/search/:input', to: 'friend#search'

  get '/friends', to: 'friend#friends_index'

  post '/friends', to: 'friend#add_friend'
  
  delete '/friends', to: 'friend#remove_friend'

  get '/all_notifications', to: 'notifications#showAllNotifications'

  get '/join/:order_id', to: 'notifications#join'
  get '/cancel/:order_id', to: 'notifications#cancel'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :user_id, presence: true
    validates :friend_id, presence: true
    validates :friend_id, uniqueness: { scope: [:user_id, :friend_id] }
    belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name, presence:true, uniqueness:true
    belongs_to :user
    has_many :user_groups
end

app/models/invited_user.rb
class InvitedUser < ApplicationRecord
    belongs_to :user
    belongs_to :order
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :from, class_name: "User", foreign_key: "from_id"
    belongs_to :to, class_name: "User", foreign_key: "to_id"


    scope :unread, ->{ where(read_at: nil) }
end

app/models/order.rb
class Order < ApplicationRecord
    validates :order_for, presence: true
    validates :restaurant, presence: true

    belongs_to :user 
    has_many :invited_users
    has_many :users, through: :invited_users

    attr_accessor :image

    has_attached_file :image
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # belongs_to :order 
  has_many :invited_users
  has_many :orders
  # has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
  # has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  # has_many :groups, :class_name => 'Group', :foreign_key => 'user_id'
  has_many :user_groups, :class_name => 'UserGroup', :foreign_key => 'user_id'       

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def email_required?
    false
  end

  has_attached_file :avatar, :default_url => "/system/users/avatars/000/000/default/user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  has_many :following, :class_name => 'Friend', :foreign_key => 'user_id'
  has_many :followers, :class_name => 'Friend', :foreign_key => 'friend_id'

  has_many :friends
  has_many :notifications, foreign_key: :to_id

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    belongs_to :user
end

app/controllers/friend_controller.rb
class FriendController < ApplicationController

  def friends_index
    @friends = User.joins("INNER JOIN friends ON users.id = friends.friend_id")
                      .where("friends.user_id"=> current_user.id);
    
    @friends
  end

  def add_friend
    @user = User.find_by(email: params[:email][:email])
    if(@user)
      @friend = Friend.new(user_id: current_user.id, friend_id: @user.id )
      if( @friend.user_id == @friend.friend_id)
        redirect_to friends_path, notice: "You can't add your self"  
      elsif @friend.save
        Notification.create(from_id: current_user.id, to_id: @friend.friend_id,notification_type: 1)
        redirect_to friends_path, notice: "Added successfully."
      elsif @friend.errors.details[:friend_id][0][:error] == :taken 
        redirect_to friends_path, notice: "Alredy your friend."
      end
    else
      redirect_to friends_path, notice: "Couldn't find a user with the email you entered."
    end
  end

  def remove_friend
    friend = Friend.find_by(friend_id: params[:format])
    if friend.destroy
      redirect_to friends_path, notice: "Removed successfully."
    else 
      redirect_to friends_path, notice: "Something went wrong, plese try again."
    end
  end


  def search
    query = params['input'];
    friends = User.joins(:followers).where(["name LIKE :query", query: "%#{query}%"]).where.not(id: current_user.id);
    if friends.length() == 0
        groups = Group.where(["name LIKE :query", query: "%#{query}%"])
        msg = { :status => "ok", :message => groups, :type => "group" }
    else
        msg = { :status => "ok", :message => friends, :type => "friend" }
    end
    
    render :json => msg
end

end
  

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user_orders = Order.where(user_id: current_user.id).reverse_order
    @friends_orders = Order.where(user_id: [current_user.friends.pluck("friend_id")]).reverse_order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_groups_helper.rb
module UsersGroupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YalaNotlobSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="overflow-x: hidden;">
  <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light" style="background: lightgray">
        <a class="navbar-brand" href=<%= root_path%>>Yala-Notlob</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="<%= root_path%>" class="btn btn-warning nav-link" >Home</a>
            </li>
            <li class="nav-item active">
              <a href="<%=friends_path%>" class="btn btn-warning nav-link" >Friends</a>
            </li>
            <li class="nav-item active">
              <a href="<%=groups_path%>" class="btn btn-warning nav-link" >Groups</a>
            </li>
            <li class="nav-item active">
              <a href="<%=orders_path%>" class="btn btn-warning nav-link" >Orders</a>
              </li>
            <li class="nav-item active">
              <a href="<%=new_order_path%>" class="btn btn-warning nav-link" >new order</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
                  <li class="nav-item btn-group active ml-auto" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
                    <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                      <span class='bell'><%= fa_icon "bell" %></span> <span class='has-badge' data-behavior="unread-count"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
                    </div>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class='active ml-auto'>
                    <%= image_tag current_user.avatar.url, :style => "width: 50px; height: 50px; border-radius: 50%; margin-right: 10px" %>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class='active ml-auto'>
                    <h6 class="mt-2" style='font-size: 20px'><%= current_user.name %></h6>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class='active ml-auto'>
                    <%= link_to "edit profile", edit_user_registration_path, method: "get", class: "btn btn-primary btn-md", :style => "margin-right:10px;margin-left:10px" %>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class='active ml-auto'>
                    <%= link_to "logout", destroy_user_session_path, method: "get", class: "btn btn-danger btn-md" %>
                  </li>
                </ul>
        </div>
      </nav>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>